appPort: 80
appName: frontend
ingress:
  enabled: true
  dnsName: www.vitingousa.live
  path: /
#resources:
#  limits:
#    cpu: 1000m
#    memory: 1024Mi
#  requests:
#    cpu: 800m
#    memory: 800Mi
java:
  xmx: "750m"
