appPort: 80
appName: frontend
ingress:
  enabled: false
#  dnsName: www.vitingousa.live
#  path: /
#resources:
#  limits:
#    cpu: 1000m
#    memory: 1024Mi
#  requests:
#    cpu: 800m
#    memory: 800Mi
java:
  xmx: "350m"